CODE WITHOUT BIAS

In [ ]:
import torch
from torch import nn

In [ ]:
input1 = torch.tensor([[1, 2, 0], [0, 3, 1], [1, 0, 1]], dtype=torch.float32)
input2 = torch.tensor([[0, 3, 1], [1, 3, 0], [2, 0, 2]], dtype=torch.float32)

In [ ]:
kernel1 = torch.tensor([[1, 0], [0, 1]], dtype=torch.float32)
kernel2 = torch.tensor([[0, 1], [1, 0]], dtype=torch.float32)
kernel3 = torch.tensor([[1, 1], [1, 0]], dtype=torch.float32)

In [ ]:
kernel1_result = torch.(input1, kernel1), torch.dot(input2, kernel1)
kernel2_result = torch.dot(input1, kernel2), torch.dot(input2, kernel2)
kernel3_result = torch.dot(input1, kernel3), torch.dot(input2, kernel3)
print("Kernel 1 Result:")
print(kernel1_result)
print("Kernel 2 Result:")
print(kernel2_result)
print("Kernel 3 Result:")
print(kernel3_result)

In [23]:
input1_conv = torch.tensor([[[5.0, 5.0], [3.0, 7.0]],  
[[6.0, 6.0], [7.0, 2.0]],  
[[6.0, 9.0], [8.0, 5.0]]]  , dtype=torch.float32)
input2_conv = torch.tensor([[[6.0, 5.0], [2.0, 6.0]], [[4.0, 5.0], [6.0, 3.0]], [[5.0, 7.0], [6.0, 6.0]]], dtype=torch.float32)
merged_batch = torch.stack([input1_conv, input2_conv])

In [24]:
batch_norm = nn.BatchNorm2d(3)
batch_norm.weight.data.fill_(1.0)
batch_norm.bias.data.fill_(0.0)
output = batch_norm(merged_batch)
print("Batch Normalization Output:")
print(output)

Batch Normalization Output:
tensor([[[[ 0.0814,  0.0814],
          [-1.2207,  1.3834]],

         [[ 0.6964,  0.6964],
          [ 1.3155, -1.7798]],

         [[-0.3780,  1.8898],
          [ 1.1339, -1.1339]]],


        [[[ 0.7324,  0.0814],
          [-1.8717,  0.7324]],

         [[-0.5417,  0.0774],
          [ 0.6964, -1.1607]],

         [[-1.1339,  0.3780],
          [-0.3780, -0.3780]]]], grad_fn=<NativeBatchNormBackward0>)


In [25]:
max_pool = nn.MaxPool2d(kernel_size=2, stride=2)
pooled_output = max_pool(output)
print("Max Pooling Output:")
print(pooled_output)

Max Pooling Output:
tensor([[[[1.3834]],

         [[1.3155]],

         [[1.8898]]],


        [[[0.7324]],

         [[0.6964]],

         [[0.3780]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


In [28]:
flatten = nn.Flatten()
flattened_output = flatten(pooled_output)
print("Flattened Output:")
print(flattened_output)

Flattened Output:
tensor([[1.3834, 1.3155, 1.8898],
        [0.7324, 0.6964, 0.3780]], grad_fn=<ViewBackward0>)


In [37]:
fully_connected = nn.Linear(in_features=flattened_output.size(1), out_features=1)
fully_connected.bias.data.fill_(1.0)
fully_connected.weight.data.fill_(0.5)
output_fc = fully_connected(flattened_output)
print("Fully Connected Layer Output:")
print(output_fc)

Fully Connected Layer Output:
tensor([[3.2944],
        [1.9034]], grad_fn=<AddmmBackward0>)


In [ ]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

In [ ]:
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3, 3),
    bias=False,
)

In [ ]:
conv_layer.weight

In [ ]:
init_kernel_weight = torch.randint(
    high=2,
    size=(conv_layer.weight.data.shape),
    dtype=torch.float32,
)
init_kernel_weight

In [ ]:
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

In [ ]:
output = conv_layer(input)
output

CODE WITH BIAS

In [ ]:
conv_layer_2 = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3, 3),
)
conv_layer_2.bias

In [ ]:
conv_layer_2.weight.data = init_kernel_weight
conv_layer_2.weight

In [ ]:
# Init bias
conv_layer_2.bias = nn.Parameter(torch.tensor([1], dtype=torch.float32))
conv_layer_2.bias

In [ ]:
output = conv_layer_2(input)
output

PADDING

In [ ]:
input = torch.randint(5, (1, 4, 4), dtype=torch.float32)
input

In [ ]:
conv_layer_3 = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3, 3),
    padding=(2, 1),
)
conv_layer.weight

In [ ]:
init_kernel_weight = torch.randint(
    high=2,
    size=conv_layer.weight.data.shape,
    dtype=torch.float32,
)
init_kernel_weight

In [ ]:
conv_layer_3.weight.data = init_kernel_weight
conv_layer_3.weight

In [ ]:
# Init bias
conv_layer_3.bias = nn.Parameter(torch.tensor([1], dtype=torch.float32))
conv_layer_3.bias

In [ ]:
output = conv_layer_3(input)
output

STRIDE

In [ ]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

In [ ]:
conv_layer_4 = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3, 3),
    stride=(2, 2),
)
conv_layer_4.weight

In [ ]:
init_kernel_weight = torch.randint(
    high=2,
    size=conv_layer.weight.data.shape,
    dtype=torch.float32,
)
init_kernel_weight
conv_layer_4.weight.data = init_kernel_weight
conv_layer_4.weight

In [ ]:
# init bias
conv_layer_4.bias = nn.Parameter(torch.tensor([1], dtype=torch.float32))
conv_layer_4.bias

In [ ]:
output = conv_layer_4(input)
output

POOLING

In [ ]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

In [ ]:
max_pool_layer = nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))

In [ ]:
output = max_pool_layer(input)
output

FLATTEN

In [ ]:
input = torch.randint(5, (1, 3, 2), dtype=torch.float32)
input

In [ ]:
flatten_layer = nn.Flatten()
output = flatten_layer(input)
output