CODE WITHOUT BIAS

In [83]:
import torch
from torch import nn

In [84]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

tensor([[[1., 0., 1., 0., 4., 2.],
         [4., 1., 3., 0., 0., 2.],
         [2., 1., 2., 3., 4., 1.],
         [0., 0., 1., 3., 3., 4.],
         [2., 3., 1., 2., 4., 0.],
         [3., 1., 3., 2., 1., 0.]]])

In [85]:
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3, 3),
    bias=False,
)

In [86]:
conv_layer.weight

Parameter containing:
tensor([[[[ 0.3294,  0.2564, -0.1350],
          [ 0.3111,  0.1978,  0.1526],
          [ 0.0393,  0.1421,  0.2897]]]], requires_grad=True)

In [87]:
init_kernel_weight = torch.randint(
    high=2,
    size=(conv_layer.weight.data.shape),
    dtype=torch.float32,
)
init_kernel_weight

tensor([[[[1., 0., 1.],
          [0., 1., 0.],
          [1., 0., 1.]]]])

In [88]:
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [0., 1., 0.],
          [1., 0., 1.]]]], requires_grad=True)

In [89]:
output = conv_layer(input)
output

tensor([[[ 7.,  7., 11.,  6.],
         [ 9.,  6., 10., 13.],
         [ 7., 10., 14.,  9.],
         [10.,  7., 10., 13.]]], grad_fn=<SqueezeBackward1>)

CODE WITH BIAS

In [90]:
conv_layer_2 = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3, 3),
)
conv_layer_2.bias

Parameter containing:
tensor([0.2474], requires_grad=True)

In [91]:
conv_layer_2.weight.data = init_kernel_weight
conv_layer_2.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [0., 1., 0.],
          [1., 0., 1.]]]], requires_grad=True)

In [92]:
# Init bias
conv_layer_2.bias = nn.Parameter(torch.tensor([1], dtype=torch.float32))
conv_layer_2.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [93]:
output = conv_layer_2(input)
output

tensor([[[ 8.,  8., 12.,  7.],
         [10.,  7., 11., 14.],
         [ 8., 11., 15., 10.],
         [11.,  8., 11., 14.]]], grad_fn=<SqueezeBackward1>)

PADDING

In [94]:
input = torch.randint(5, (1, 4, 4), dtype=torch.float32)
input

tensor([[[4., 2., 1., 2.],
         [4., 2., 0., 4.],
         [3., 2., 3., 1.],
         [0., 3., 3., 1.]]])

In [95]:
conv_layer_3 = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3, 3),
    padding=(2, 1),
)
conv_layer.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [0., 1., 0.],
          [1., 0., 1.]]]], requires_grad=True)

In [96]:
init_kernel_weight = torch.randint(
    high=2,
    size=conv_layer.weight.data.shape,
    dtype=torch.float32,
)
init_kernel_weight

tensor([[[[0., 0., 0.],
          [0., 1., 1.],
          [0., 0., 1.]]]])

In [97]:
conv_layer_3.weight.data = init_kernel_weight
conv_layer_3.weight

Parameter containing:
tensor([[[[0., 0., 0.],
          [0., 1., 1.],
          [0., 0., 1.]]]], requires_grad=True)

In [98]:
# Init bias
conv_layer_3.bias = nn.Parameter(torch.tensor([1], dtype=torch.float32))
conv_layer_3.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [99]:
output = conv_layer_3(input)
output

tensor([[[3., 2., 3., 1.],
         [9., 4., 8., 3.],
         [9., 6., 6., 5.],
         [9., 9., 6., 2.],
         [4., 7., 5., 2.],
         [1., 1., 1., 1.]]], grad_fn=<SqueezeBackward1>)

STRIDE

In [100]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

tensor([[[1., 4., 1., 4., 2., 4.],
         [2., 3., 3., 4., 2., 3.],
         [1., 3., 4., 0., 0., 1.],
         [3., 4., 3., 3., 1., 0.],
         [0., 4., 2., 1., 3., 3.],
         [3., 4., 1., 4., 4., 3.]]])

In [101]:
conv_layer_4 = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3, 3),
    stride=(2, 2),
)
conv_layer_4.weight

Parameter containing:
tensor([[[[-0.0488, -0.2789, -0.0849],
          [-0.0161, -0.2296, -0.1609],
          [-0.2498, -0.2781, -0.2217]]]], requires_grad=True)

In [102]:
init_kernel_weight = torch.randint(
    high=2,
    size=conv_layer.weight.data.shape,
    dtype=torch.float32,
)
init_kernel_weight
conv_layer_4.weight.data = init_kernel_weight
conv_layer_4.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [0., 0., 0.],
          [0., 0., 0.]]]], requires_grad=True)

In [103]:
# init bias
conv_layer_4.bias = nn.Parameter(torch.tensor([1], dtype=torch.float32))
conv_layer_4.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [104]:
output = conv_layer_4(input)
output

tensor([[[3., 4.],
         [6., 5.]]], grad_fn=<SqueezeBackward1>)

POOLING

In [105]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

tensor([[[2., 3., 3., 3., 0., 2.],
         [3., 1., 1., 0., 0., 0.],
         [4., 3., 1., 0., 3., 4.],
         [0., 1., 2., 3., 4., 2.],
         [3., 4., 4., 4., 2., 3.],
         [4., 4., 2., 1., 3., 1.]]])

In [106]:
max_pool_layer = nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))

In [107]:
output = max_pool_layer(input)
output

tensor([[[3., 3., 2.],
         [4., 3., 4.],
         [4., 4., 3.]]])

FLATTEN

In [112]:
input = torch.randint(5, (1, 3, 2), dtype=torch.float32)
input

tensor([[[4., 4.],
         [1., 1.],
         [1., 0.]]])

In [113]:
flatten_layer = nn.Flatten()
output = flatten_layer(input)
output

tensor([[4., 4., 1., 1., 1., 0.]])