In [1]:
import torch
import torchvision.transforms as transforms
from torch import nn
import torch.nn.functional as F
import numpy as np

In [2]:
data = np.array([[[1, 6], [3, 4]]])
data = torch.tensor(data, dtype=torch.float32)

batch_norm = nn.BatchNorm2d(1)
data = data.unsqueeze(0)  # Add batch dimension
with torch.no_grad():
    output = batch_norm(data)
    print(output)

tensor([[[[-1.3867,  1.3867],
          [-0.2773,  0.2773]]]])


In [3]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

a = a.reshape(1, 2, 2)
b = b.reshape(1, 2, 2)

c = torch.cat((a, b))
print(c)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [6]:
seed = 1
torch.manual_seed(seed)
input_tensor = torch.tensor([[[[1.0, 2.0], [3.0, 4.0]]]])
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=1)
conv_output = conv_layer(input_tensor)

with torch.no_grad():
    conv_output = conv_layer(input_tensor) + input_tensor
    print(conv_output)

tensor([[[[1.0739, 2.5891],
          [4.1044, 5.6197]]]])
