In [5]:
import torch
import torch.nn as nn

BATCH NORM

In [6]:
input = torch.randint(5, (4, 3), dtype=torch.float32)
input

tensor([[0., 1., 1.],
        [0., 1., 4.],
        [1., 2., 3.],
        [2., 1., 1.]])

In [9]:
batch_norm_layer = nn.BatchNorm1d(num_features=3) # With 3 features of tensor above
batch_norm_layer.weight
batch_norm_layer.bias

Parameter containing:
tensor([0., 0., 0.], requires_grad=True)

In [10]:
output = batch_norm_layer(input)
output

tensor([[-0.9045, -0.5773, -0.9622],
        [-0.9045, -0.5773,  1.3471],
        [ 0.3015,  1.7320,  0.5773],
        [ 1.5075, -0.5773, -0.9622]], grad_fn=<NativeBatchNormBackward0>)

DROPOUT

In [11]:
model = nn.Sequential(
    nn.Flatten(),
    nn.Linear(3*2, 5),
    nn.ReLU(),
    nn.Dropout(0.2),
    nn.Linear(5, 2),
)

In [12]:
for p in model.parameters():
    print(p)

Parameter containing:
tensor([[ 0.1707, -0.2601,  0.2058,  0.3536, -0.2757,  0.0919],
        [ 0.0482, -0.1449,  0.0964, -0.1117, -0.0353, -0.0829],
        [-0.3608,  0.0361,  0.3839,  0.0516,  0.0736,  0.0121],
        [-0.3642, -0.3233, -0.0645, -0.1181, -0.3405,  0.1251],
        [ 0.3036, -0.1293,  0.2550,  0.3439, -0.3321, -0.0536]],
       requires_grad=True)
Parameter containing:
tensor([-0.1336,  0.2753, -0.0932,  0.3997, -0.0616], requires_grad=True)
Parameter containing:
tensor([[ 0.0473,  0.2128, -0.1982, -0.3846,  0.1435],
        [ 0.3533, -0.0346,  0.0158,  0.2009, -0.0377]], requires_grad=True)
Parameter containing:
tensor([-0.2490, -0.0960], requires_grad=True)
