In [17]:
import numpy as np

In [18]:
X = np.array([
    [0.5],
    [1.0],
    [1.5],
    [2.0],
    [2.5],
    [3.0],
    [3.5],
    [4.0],
])

Y = np.array([0, 0, 0, 1, 0, 0, 1, 1, 1])

In [19]:
def convert_one_hot(y, k):
    one_hot = np.zeros((len(y), k))
    one_hot[np.arange(len(y)), y] = 1
    return one_hot

n_classes = 2
Y_one_hot = convert_one_hot(Y, n_classes)
print(Y_one_hot)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [20]:
X = np.hstack([np.ones((X.shape[0], 1)), X])
print(X)

[[1.  0.5]
 [1.  1. ]
 [1.  1.5]
 [1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [1.  4. ]]


In [21]:
x = X[0].reshape((2, 1))
print(x)
y = Y_one_hot[0].reshape((2, 1))
print(y)


[[1. ]
 [0.5]]
[[1.]
 [0.]]


In [22]:
theta = np.array([[0.1, 0.2], [0.3, 0.4]])
print(theta)

[[0.1 0.2]
 [0.3 0.4]]


In [23]:
def softmax_fn(z):
    return np.exp(z) / np.sum(np.exp(z))

def predict(x, theta):
    z = theta.T.dot(x)
    y_hat = softmax_fn(z)
    return z, y_hat

z, y_hat = predict(x, theta)
print(z)
print(y_hat)

[[0.25]
 [0.4 ]]
[[0.46257015]
 [0.53742985]]


In [24]:
def compute_loss(y_hat, y):
    loss = -np.log(y.T.dot(y_hat))
    return loss

loss = compute_loss(y_hat, y)
loss

array([[0.77095705]])

In [26]:
def compute_gradient(y_hat, y, x):
    gradient = x.dot((y_hat - y).T)
    return gradient

gradient = compute_gradient(y_hat, y, x)
gradient

array([[-0.53742985,  0.53742985],
       [-0.26871492,  0.26871492]])

In [27]:
learning_rate = 0.01

def update_weight(theta, gradient, learning_rate):
    theta -= (learning_rate * gradient)
    return theta

theta = update_weight(theta, gradient, learning_rate)
theta

array([[0.1053743 , 0.1946257 ],
       [0.30268715, 0.39731285]])