In [129]:
import numpy as np
import matplotlib.pyplot as plt

BASIC LOGISTIC REGRESSION

Sample 1

In [130]:
x = np.array([1.0, 0.5])
y = np.array([0])

In [131]:
x.shape, y.shape

((2,), (1,))

In [132]:
theta = np.array([0.1, 0.1])
theta.shape

(2,)

In [133]:
z = np.dot(theta.T, x)
z

np.float64(0.15000000000000002)

In [134]:
# Logistic function
def logistic_fn(x):
    return 1 / (1 + np.exp(-x))

In [135]:
y_hat = logistic_fn(z)
print(f"{y_hat:.2f}")

0.54


In [136]:
# Compute loss
loss = (-1 * y) * np.log(y_hat) - (1 - y) * np.log(1 - y_hat)
float(loss[0])

0.7709570477895322

In [137]:
# Compute derivation
gradient = x*(y_hat - y)
gradient

array([0.53742985, 0.26871492])

In [138]:
# Update parameter
LEARNING_RATE = 0.1
theta -= (LEARNING_RATE * gradient)
theta

array([0.04625702, 0.07312851])

In [139]:
z = np.dot(theta.T , x)
z

np.float64(0.08282126933203131)

In [140]:
y_hat = logistic_fn(z)
y_hat

np.float64(0.520693490005697)

In [141]:
# Compute loss
loss = (-1 * y) * np.log(y_hat) - (1 - y) * np.log(1 - y_hat)
float(loss[0])

0.7354149906131442

Sample 2

In [142]:
X = np.array([1.0, 1.0])
y = np.array([0])

In [143]:
z = np.dot(theta.T, x)
z

np.float64(0.08282126933203131)

In [144]:
y_hat = logistic_fn(z)
print(f"{y_hat:.2f}")

0.52


In [145]:
# Compute loss
loss = (-1 * y) * np.log(y_hat) - (1 - y) * np.log(1 - y_hat)
float(loss[0])

0.7354149906131442

In [146]:
# Compute derivation
gradient = x*(y_hat - y)
gradient

array([0.52069349, 0.26034675])

In [147]:
# Update parameter
LEARNING_RATE = 0.1
theta -= (LEARNING_RATE * gradient)
theta

array([-0.00581233,  0.04709383])

TEST SAMPLE

In [148]:
x_test = np.array([1.0, 0.25])
z = np.dot(theta.T, x_test)
y_hat = logistic_fn(z)
y_hat

np.float64(0.5014902767802163)

In [149]:
x_test = np.array([1.0, 4.5])
z = np.dot(theta.T, x_test)
y_hat = logistic_fn(z)
y_hat

np.float64(0.5513458377524659)

Sample 3

In [152]:
x = np.array([1.0, 1.0, 0.5])
y = np.array([0])
x.shape, y.shape

((3,), (1,))

In [151]:
theta = np.array([0.1, 0.2, 0.1])
theta

array([0.1, 0.2, 0.1])

In [156]:
# Forward
def predict(x, theta):
    z = np.dot(theta.T, x)
    y_hat = logistic_fn(z)
    return z, y_hat

z, y_hat = predict(x, theta)

In [157]:
z, y_hat

(np.float64(0.35000000000000003), np.float64(0.5866175789173301))

In [158]:
# Compute loss
def compute_loss(y_hat, y):
    loss = (-1 * y) * np.log(y_hat) - (1 - y) * np.log(1 - y_hat)
    return loss

loss = compute_loss(y_hat, y)
loss

array([0.88338216])

In [160]:
# Compute gradient
def compute_gradient(x, y_hat, y):
    gradient = x * (y_hat - y)
    return gradient

gradient = compute_gradient(x, y_hat, y)
gradient

array([0.58661758, 0.58661758, 0.29330879])

In [161]:
# Update weight
def update_weight(gradient, theta, LEARNING_RATE=0.1):
    theta -= (LEARNING_RATE * gradient)
    return theta
theta = update_weight(gradient, theta)
theta

array([0.04133824, 0.14133824, 0.07066912])

Prediction

In [162]:
x_test = np.array([1.0, 2.0, 0.25])
z = np.dot(theta.T , x_test)
y_hat = logistic_fn(z)
z, y_hat

(np.float64(0.34168200658833436), np.float64(0.5845990444988789))

In [163]:
x_test = np.array([1.0, 2.0, 4.5])
z = np.dot(theta.T , x_test)
y_hat = logistic_fn(z)
z, y_hat

(np.float64(0.6420257710684018), np.float64(0.6552112452546174))