In [127]:
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [128]:
vectorizer = CountVectorizer()
corpus = ["góp gió gặt bão",
          "có làm mới có ăn",
          "đất lành chim đậu",
          "ăn cháo đá bát",
          "gậy ông đập lưng ông",
          "qua cầu rút ván"]
x_data = vectorizer.fit_transform(corpus)
x_data = x_data.toarray()

In [129]:
print(x_data)
print(x_data.shape)

[[0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 2 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]]
(6, 23)


In [130]:
y_data = np.array([1, 1, 1, 0, 0, 0])
y_data

array([1, 1, 1, 0, 0, 0])

In [131]:
x_test = vectorizer.transform(['không làm cạp đất mà ăn']).toarray()
x_test

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0]])

In [132]:
# Compute distances
distances = np.sqrt(np.sum((x_data - x_test)**2, axis=1))
print(distances)

[2.64575131 2.44948974 2.23606798 2.23606798 3.16227766 2.64575131]


In [133]:
# Get top k
top_k = np.argsort(distances)
print(top_k)

k = 3
top_k = top_k[:k]
print(top_k)

[3 2 1 0 5 4]
[3 2 1]


In [134]:
value_y_data = y_data[top_k]
print(value_y_data)

number_of_ones = np.sum(value_y_data == 1)
number_of_zeros = np.sum(value_y_data == 0)

if number_of_ones > number_of_zeros:
    print("1")
else:
    print("0")

[0 1 1]
1


USING LIB

In [135]:
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_data, y_data)

y_pred = classifier.predict(x_test)
print(y_pred)

[1]
