In [2]:
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [3]:
vectorizer = CountVectorizer()
corpus = ["góp gió gặt bão",
          "có làm mới có ăn",
          "đất lành chim đậu",
          "ăn cháo đá bát",
          "gậy ông đập lưng ông",
          "qua cầu rút ván"]


## HAND

In [4]:
x_data = vectorizer.fit_transform(corpus)
x_data = x_data.toarray()

In [5]:
print(x_data)
print(x_data.shape)

[[0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 2 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]]
(6, 23)


In [6]:
y_data = np.array([1, 1, 1, 0, 0, 0])
y_data

array([1, 1, 1, 0, 0, 0])

In [7]:
x_test = vectorizer.transform(['không làm cạp đất mà ăn']).toarray()
x_test

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0]])

In [8]:
# Compute distances
distances = np.sqrt(np.sum((x_data - x_test)**2, axis=1))
print(distances)

[2.64575131 2.44948974 2.23606798 2.23606798 3.16227766 2.64575131]


In [9]:
# Get top k
top_k = np.argsort(distances)
print(top_k)

k = 3
top_k = top_k[:k]
print(top_k)

[3 2 1 0 5 4]
[3 2 1]


In [10]:
value_y_data = y_data[top_k]
print(value_y_data)

number_of_ones = np.sum(value_y_data == 1)
number_of_zeros = np.sum(value_y_data == 0)

if number_of_ones > number_of_zeros:
    print("1")
else:
    print("0")

[0 1 1]
1


USING LIB

In [12]:
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_data, y_data)

y_pred = classifier.predict(x_test)
print(y_pred)
x_data = vectorizer.fit_transform(corpus)
x_data = x_data.toarray()

[1]


## USING LIBRARY

In [27]:
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import numpy as np

In [28]:
n_doc = len(corpus)

labels = [1, 1, 1, 0, 0, 0] # 1: positive - 0: negative

cate_2_label = {
    "positive": 1,
    "negative": 0
}

In [29]:
def label_2_cate(labels):
    key_list = list(cate_2_label.keys())
    val_list = list(cate_2_label.values())

    position = [val_list.index(label) for label in labels]
    return np.array(key_list)[position]

In [30]:
X = np.array(corpus)
print(f"X: {X}")
y = np.array(labels)
print(f"y: {y}")

X: ['góp gió gặt bão' 'có làm mới có ăn' 'đất lành chim đậu' 'ăn cháo đá bát'
 'gậy ông đập lưng ông' 'qua cầu rút ván']
y: [1 1 1 0 0 0]


### CONVERT TEXT TO VECTOR BY USING TF-IDF transform

In [31]:
def caculate_tfidf(X_vectorized):
    tf = np.log(X_vectorized + 1)
    df = np.sum(X_vectorized, axis= 0)
    idf = np.log((n_doc+1)/(df+1)) + 1
    tfidf = tf * idf

    return idf, tf, tfidf

In [32]:
def compute_norm(tfidf_vec):
    norm = np.linalg.norm(tfidf_vec, axis = 1)
    n_doc = tfidf_vec.shape[0]
    for i in range(n_doc):
        tfidf_vec[i] /=  norm[i]

In [33]:
vectorizer = CountVectorizer()
X_vectorized = vectorizer.fit_transform(X).toarray()
print("Vocab: ", vectorizer.get_feature_names_out())

Vocab:  ['bát' 'bão' 'chim' 'cháo' 'có' 'cầu' 'gió' 'góp' 'gậy' 'gặt' 'làm' 'lành'
 'lưng' 'mới' 'qua' 'rút' 'ván' 'ông' 'ăn' 'đá' 'đất' 'đập' 'đậu']


In [34]:
X_idf, X_tf, X_tfidf = caculate_tfidf(X_vectorized)
print(f"X_idf: {X_idf}")
print(f"shape x_idf: {X_idf.shape}")
print(f"x_tf: {X_tf}")
print(f"shape X_tf: {X_tf.shape}")
print(f"X_tfidf: {X_tfidf}")
print(f"shape X_tfidf: {X_tfidf.shape}")

X_idf: [2.25276297 2.25276297 2.25276297 2.25276297 1.84729786 2.25276297
 2.25276297 2.25276297 2.25276297 2.25276297 2.25276297 2.25276297
 2.25276297 2.25276297 2.25276297 2.25276297 2.25276297 1.84729786
 1.84729786 2.25276297 2.25276297 2.25276297 2.25276297]
shape x_idf: (23,)
x_tf: [[0.         0.69314718 0.         0.         0.         0.
  0.69314718 0.69314718 0.         0.69314718 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         1.09861229 0.
  0.         0.         0.         0.         0.69314718 0.
  0.         0.69314718 0.         0.         0.         0.
  0.69314718 0.         0.         0.         0.        ]
 [0.         0.         0.69314718 0.         0.         0.
  0.         0.         0.         0.         0.         0.69314718
  0.         0.         0.         0.         0.         0.
  0.         0.         0.69314718 0.         

In [35]:
compute_norm(X_tfidf)

### TRAIN MODEL

In [36]:
knn_cls = KNeighborsClassifier(n_neighbors=3)
knn_cls.fit(X_tfidf, y)
preds = knn_cls.predict(X_tfidf)
print(preds)

[1 0 1 1 1 1]


### USING PIPELINE OF SKLEARN

In [37]:
text_clf_model = Pipeline([('vect', CountVectorizer()),
                            ('tfidf', TfidfTransformer()),
                            ('clf', KNeighborsClassifier(n_neighbors=1)),
                        ])

text_clf_model.fit(X, y)

preds = text_clf_model.predict(X)
print(preds)

[1 1 1 0 0 0]


### INFERENCE

In [38]:
test_text = np.array(["không làm cạp đất mà ăn"])
test_vec = vectorizer.transform(test_text).toarray()

In [39]:
test_tf = np.log(test_vec + 1)
test_tfidf = test_tf * X_idf

In [40]:
compute_norm(test_tfidf)

In [41]:
pred = knn_cls.predict(test_tfidf)

print(label_2_cate(pred))

['positive']
