In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("./data/iris_2D.csv")
data

,Petal_Length,Petal_Width,Label
0,1.4,0.2,0.0
1,1.3,0.4,0.0
2,1.4,0.3,0.0
3,4.0,1.0,1.0
4,4.7,1.4,1.0
5,3.6,1.3,1.0


In [3]:
# Get x
x_data = data[["Petal_Length", "Petal_Width"]].to_numpy()
x_data.reshape(6, 2)
x_data

array([[1.4, 0.2],
       [1.3, 0.4],
       [1.4, 0.3],
       [4. , 1. ],
       [4.7, 1.4],
       [3.6, 1.3]])

In [4]:
# Get y
y_data = data["Label"].to_numpy()
y_data

array([0., 0., 0., 1., 1., 1.])

In [5]:
x_test = np.array([[2.4, 0.8]])
x_test

array([[2.4, 0.8]])

IMPLEMENT SIMPLE KNN 2D

In [6]:
# COMPUTE DISTANCES
distances = np.sqrt(np.sum(np.square(x_data - x_test), axis=1))
print(distances)

[1.16619038 1.17046999 1.11803399 1.61245155 2.37697286 1.3       ]


In [7]:
# Get the top k
top_k = np.argsort(distances)
print(f"Index of sorting nearest neighbors: {top_k}")

k = 3
top_k = top_k[:k]
print(f"Index of top {k} nearest neighbors: {top_k}")

Index of sorting nearest neighbors: [2 0 1 5 3 4]
Index of top 3 nearest neighbors: [2 0 1]


In [8]:
# Get corresponding y values
values_top_k = y_data[top_k]
print(f"Values of top {k} nearest neighbors: {values_top_k}")

Values of top 3 nearest neighbors: [0. 0. 0.]


In [10]:
# Get majortiy
num_zeros = np.sum(values_top_k == 0)
num_ones = np.sum(values_top_k == 1)
print(f"Number of zeros: {num_zeros}")
print(f"Number of ones: {num_ones}")

# classification
if num_zeros > num_ones:
    print("The class is 0")
else:
    print("The class is 1")

Number of zeros: 3
Number of ones: 0
The class is 0


IMPLEMENT USING LIB

In [11]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_data, y_data)

y_pred = classifier.predict(x_test)
print(y_pred)

[0.]
