In [52]:
import numpy as np

In [53]:
def predict(X:np.ndarray, theta:np.ndarray) -> np.ndarray:
    z = np.dot(theta.T, X)
    y_hat = 1/(1 + np.exp(-z))
    return z, y_hat

def compute_loss(y_hat, y):
    N = y.shape[0]
    loss = (-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))/N

    return loss

def compute_gradient(y_hat, y, X):
    N = y.shape[0]
    diff = (y_hat - y)
    return X*diff / N

def update_gradient(theta, gradient, lr):
    theta -= lr*gradient
    return theta

In [54]:
X = np.array([1.0, 1.0, 0.5])
print(X.shape)
y = np.array([0])
print(y.shape)
theta = np.array([0.1, 0.2, 0.1])
print(theta.shape)

(3,)
(1,)
(3,)


In [55]:
z, y_hat = predict(X, theta)
z.shape, y_hat.shape

((), ())

In [56]:
loss = compute_loss(y_hat, y)
loss

array([0.88338216])

In [57]:
gradient = compute_gradient(y_hat, y, X)
gradient

array([0.58661758, 0.58661758, 0.29330879])

In [58]:
learning_rate = 0.1
theta = update_gradient(theta, gradient, learning_rate)
theta

array([0.04133824, 0.14133824, 0.07066912])